[package]
name = "xivrepo"
version = "0.1.0"
#Team members, please add your emails and usernames
authors = ["Yagi <koruten@gmail.com>","geometrically <jai.a@tuta.io>", "Redblueflame <contact@redblueflame.com>", "Aeledfyr <aeledfyr@gmail.com>", "Charalampos Fanoulis <yo@fanoulis.dev>", "AppleTheGolden <scotsbox@protonmail.com>"]
edition = "2018"

[[bin]]
name = "xivrepo"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.1.0"
actix-rt = "1.1.1"
actix-files = "0.4.0"
actix-multipart = "0.3.0"
actix-cors = "0.5.4"
actix-ratelimit = "0.3.0"

meilisearch-sdk = "0.8.0"
reqwest = { version = "0.10.8", features = ["json"] }

yaserde = "0.6.0"
yaserde_derive = "0.7.0"
xml-rs = "0.8.3"

serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_with = "1.5.1"
chrono = { version = "0.4", features = ["serde"] }
rand = "0.8.3"
base64 = "0.13.0"
sha1 = { version = "0.6.0", features = ["std"] }
sha2 = "0.9.2"
bitflags = "1.2.1"

gumdrop = "0.8.0"
dotenv = "0.15"
log = "0.4.8"
env_logger = "0.8.1"
thiserror = "1.0.21"
lazy_static = "1.4.0"
slugify = "0.1.0"

futures = "0.3.6"
futures-timer = "3.0.2"
rust-s3 = "0.26.1"
async-trait = "0.1.41"

sqlx = { version = "0.4.2", features = ["runtime-actix-rustls", "postgres", "chrono", "offline", "macros", "migrate"] }

sentry = { version = "0.22.0", features = ["log"] }
sentry-actix = "0.22.0"
