ALTER TABLE users ADD COLUMN show_nsfw BOOLEAN NOT NULL DEFAULT '0';
ALTER TABLE mods ADD COLUMN is_nsfw BOOLEAN NOT NULL DEFAULT '0';
ALTER TABLE mods DROP COLUMN license;
ALTER TABLE mods DROP COLUMN license_url;
ALTER TABLE mods DROP COLUMN client_side;
ALTER TABLE mods DROP COLUMN server_side;