name: Deploy ApiServer

on:
  push:
    branches:
      - develop
      - release

jobs:
  deploy:
    runs-on: [self-hosted, deploy]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Build
        run: docker build . --file Dockerfile --tag xivrepo/apiserver-${GITHUB_REF##*/}:${{ github.sha }}

      -
        name: Deploy
        run: |
          pushd /compose/${GITHUB_REF##*/}-api-server
          docker-compose down
          TAG=${{ github.sha }} docker-compose up -d
          popd
